/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-08 08:12:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.OrderDTO;
import com.dto.MemberDTO;
import com.dto.CartDTO;

public final class orderDone_005fstu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.OrderDTO");
    _jspx_imports_classes.add("com.dto.MemberDTO");
    _jspx_imports_classes.add("com.dto.CartDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");

	OrderDTO dto = (OrderDTO)request.getAttribute("orderDTO");
	String userid = dto.getUserid();
	String orderName = dto.getOrderName();
	String post = dto.getPost();
	String addr1 = dto.getAddr1();
	String addr2 = dto.getAddr2();
	String phone = dto.getPhone();
	
	String gName = dto.getgName();
	int gPrice = dto.getgPrice();
	int gAmount = dto.getgAmount();
	String payMethod = dto.getPayMethod();
	

      out.write("\r\n");
      out.write("<table width=\"70%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><b>주문완료</b></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\"><b>주문해주셔서 감사합니다.</b></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"7\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\"><b>");
      out.print(userid );
      out.write("</b> 님의 주문이\r\n");
      out.write("\t\t\t안전하게 처리되었습니다.</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"td_default\"><b>상품 및 배송정보</b>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"15\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"1\" style=\"border-collapse: collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" width=\"150\" height=\"35\"> 받으시는 분</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\">");
      out.print(orderName );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\"> 주소</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\">(");
      out.print(post );
      out.write(")<br>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;");
      out.print(addr1 );
      out.write("<br>");
      out.print(addr2 );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\"> 휴대전화</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\">");
      out.print(phone );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</td>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"20\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"1\" style=\"border-collapse: collapse\"\r\n");
      out.write("\t\t\t\tbordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"250\" class=\"td_default\" height=\"35\" align=\"center\"><strong>상품명</strong></td>\r\n");
      out.write("\t\t\t\t\t<td width=\"100\" class=\"td_default\" height=\"35\" align=\"center\"><strong>판매가</strong></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" width=\"50\" height=\"35\" align=\"center\"><strong>수량</strong></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" width=\"100\" height=\"35\" align=\"center\"><strong>합계</strong></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"a_default\">");
      out.print( gName );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td height=\"35\" class=\"td_default\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<span  id = \"price1\">");
      out.print(gPrice );
      out.write("</span>원\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td height=\"35\" class=\"td_default\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<span id = \"num1\">");
      out.print(gAmount );
      out.write("</span> 개\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td height=\"35\" class=\"td_default\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( gAmount*gPrice );
      out.write("</span>원\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"td_default\"><b>결제정보</b></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"15\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"1\" style=\"border-collapse: collapse\"\r\n");
      out.write("\t\t\t\tbordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" width=\"150\" height=\"35\"> 결제금액</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\" align = 'right'> \r\n");
      out.write("\t\t\t\t\t<input type = 'text' id = 'total' value = '");
      out.print( gAmount*gPrice );
      out.write("' readonly>원\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" width=\"150\" height=\"35\"> 결제수단</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_default\" height=\"35\" align = 'right'> \r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(payMethod );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<!-- <td class=\"td_default\" align=\"center\"><a class=\"a_default\"\r\n");
      out.write("\t\t\thref=\"OrderListDetailServlet?mem_id=guest\">주문조회 페이지로 이동</a></td> -->\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\"><a class=\"a_default\"\r\n");
      out.write("\t\t\thref=\"CartListServlet\">주문조회 페이지로 이동</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
