/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-08 08:04:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.MemberDTO;
import com.dto.CartDTO;

public final class orderConfirm_005fstu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.MemberDTO");
    _jspx_imports_classes.add("com.dto.CartDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//배송지 정보 일치 체크박스\r\n");
      out.write("\t\t$(\"#same\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlet check = this.checked;\r\n");
      out.write("\t\t\tconsole.log(check)\r\n");
      out.write("\t\t\tif(check) {\r\n");
      out.write("\t\t\t\tconsole.log(true);\r\n");
      out.write("\t\t\t\t$(\"#orderName\").val($(\"#mname\").val());\r\n");
      out.write("\t\t\t\t$(\".post\").val($(\"#mpost\").val());\r\n");
      out.write("\t\t\t\t$(\".address1\").val($(\"#maddress1\").val());\r\n");
      out.write("\t\t\t\t$(\".address2\").val($(\"#maddress2\").val());\r\n");
      out.write("\t\t\t\t$(\"#phone\").val($(\"#mphone\").val());\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tconsole.log(false);\r\n");
      out.write("\t\t\t\t$(\"#orderName\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\".post\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\".address1\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\".address2\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#phone\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});// end sameFn\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//배송지 정보 입력 확인\r\n");
      out.write("\t\t$(\"form\").on(\"submit\", function(){\r\n");
      out.write("\t\t\tif($(\"#orderName\").val().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"이름을 입력하시오\");\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if($(\".post\").val().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"우편번호를 입력하시오\");\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if($(\".address1\").val().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"주소를 입력하시오\");\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if($(\".address2\").val().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"상세주소를 입력하시오\");\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} else if($(\"#phone\").val().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"전화번호를 입력하시오\");\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}); //end formFn\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");

	MemberDTO mDTO = (MemberDTO) request.getAttribute("mDTO");
String userid = mDTO.getUserid();
String username = mDTO.getUsername();
String post = mDTO.getPost();
String addr1 = mDTO.getAddr1();
String addr2 = mDTO.getAddr2();
String phone = mDTO.getPhone1()+mDTO.getPhone2()+mDTO.getPhone3();

CartDTO cDTO = (CartDTO) request.getAttribute("cDTO");
int num = cDTO.getNum();
String gCode = cDTO.getgCode();
String gName = cDTO.getgName();
int gPrice = cDTO.getgPrice();
String gSize = cDTO.getgSize();
String gColor = cDTO.getgColor();
int gAmount = cDTO.getgAmount();
String gImage = cDTO.getgImage();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 수정 부분 -->\r\n");
      out.write("<!-- hidden 처리-->\r\n");
      out.write("<form name=\"myForm\" method=\"get\" action=\"CartOrderDoneServlet\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"orderNum\" value=\"");
      out.print(num);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gCode\" value=\"");
      out.print(gCode);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gName\" value=\"");
      out.print(gName);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gPrice\" value=\"");
      out.print(gPrice);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gSize\" value=\"");
      out.print(gSize);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gColor\" value=\"");
      out.print(gColor);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gAmount\" value=\"");
      out.print(gAmount);
      out.write("\"> \r\n");
      out.write("\t<input type=\"hidden\" name=\"gImage\" value=\"");
      out.print(gImage);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"80%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>주문상품 확인</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"15\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"5\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\"><strong>주문번호</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>상품정보</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\"><strong>판매가</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>수량</strong></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" width=\"80\">");
      out.print(num );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" width=\"80\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/items/");
      out.print(gImage );
      out.write(".gif\" border=\"0\" align=\"center\" width=\"80\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" width=\"300\" style='padding-left: 30px'><br> \r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" color=\"#665b5f\">[옵션 : 사이즈(");
      out.print(gSize );
      out.write(") ,색상(");
      out.print(gColor );
      out.write(")] </font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\" width=\"110\">");
      out.print(gPrice );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"center\" width=\"90\">");
      out.print(gAmount );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"30\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align=\"right\">총 결제 금액 :</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" align='right'>");
      out.print(gPrice*gAmount );
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  고객 정보 시작-->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>고객 정보</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"15\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\" style=\"border-collapse: collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"125\" height=\"35\" class=\"td_default\">이 름</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"mname\" size=\"20\" maxlength=\"20\" value=\"");
      out.print(username);
      out.write("\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">우편번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"mpost\" size=\"6\" maxlength=\"6\" value=\"");
      out.print(post );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">주 소</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"maddress1\" size=\"35\" maxlength=\"200\" value=\"");
      out.print(addr1 );
      out.write("\" readonly></input><br> \r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"maddress2\" size=\"35\" maxlength=\"200\" value=\"");
      out.print(addr2 );
      out.write("\" readonly></input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">휴대전화</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"mphone\" size=\"15\" maxlength=\"15\" value=\"");
      out.print(phone);
      out.write("\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!--  고객 정보 끝-->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"td_default\"><input type=\"checkbox\" name=\"same\" id=\"same\"> <label for=\"same\">배송지가 동일할 경우 선택하세요.</label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!--  배송지 정보 시작-->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>배송지 정보</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"15\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\" style=\"border-collapse: collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"125\" height=\"35\" class=\"td_default\">이 름</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"orderName\" name=\"orderName\" size=\"20\" maxlength=\"20\" value=\"\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">우편번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 다음주소 시작--> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"post\" id=\"sample4_postcode\" class=\"post\"placeholder=\"우편번호\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample4_execDaumPostcode()\"  value=\"우편번호 찾기\"><br> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"addr1\" id=\"sample4_roadAddress\" class=\"address1\" placeholder=\"도로명주소\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"addr2\" id=\"sample4_jibunAddress\" class=\"address2\" placeholder=\"지번주소\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"guide\" style=\"color: #999\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<br> <!-- 다음주소 끝 -->\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">휴대전화</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input_default\" type=\"text\" id=\"phone\" name=\"phone\" size=\"15\" maxlength=\"15\" value=\"\"></input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!--  배송지 정보 끝-->\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>결제수단</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"15\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"1\" style=\"border-collapse: collapse\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"125\" height=\"35\" class=\"td_default\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"payMethod\" value=\"신용카드\" checked>신용카드</input> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"payMethod\" value=\"계좌이체\">계좌이체</input> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"payMethod\" value=\"무통장 입금\">무통장 입금</input>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"td_default\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type='button' value='취소' onclick=\"javascript:history.back()\">\r\n");
      out.write("\t\t\t\t<input type='submit' value='결제하기'>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\tfunction sample4_execDaumPostcode() {\r\n");
      out.write("\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\tif (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\tif (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\tif (fullRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\tfullRoadAddr += extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t\t\t\t\t\tif (data.autoRoadAddress) {\r\n");
      out.write("\t\t\t\t\t\t\t//예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tvar expRoadAddr = data.autoRoadAddress\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '(예상 도로명 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else if (data.autoJibunAddress) {\r\n");
      out.write("\t\t\t\t\t\t\tvar expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '(예상 지번 주소 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('guide').innerHTML = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}).open();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
