/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-08 08:04:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.CartDTO;
import com.dto.GoodsDTO;
import java.util.List;

public final class cartList_005fstu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.GoodsDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dto.CartDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    \t//전체 선택\r\n");
      out.write("    \t$(\"#allCheck\").on(\"click\", function() {\r\n");
      out.write("    \t\tconst result = this.checked;\r\n");
      out.write("    \t\t$(\".check\").each(function() {\r\n");
      out.write("    \t\t\tthis.checked = result;\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t//삭제 버튼\r\n");
      out.write("    \t$(\".delBtn\").on(\"click\", function() {\r\n");
      out.write("    \t\tconst num = $(this).attr(\"data-xxx\");\r\n");
      out.write("    \t\tlocation.href=\"CartDelServlet?num=\"+num;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t//수량 수정 버튼\r\n");
      out.write("    \t$(\".updateBtn\").on(\"click\", function() {\r\n");
      out.write("    \t\tconst num = $(this).attr(\"data-xxx\");\r\n");
      out.write("    \t\tconst gAmount = $(\"#cartAmount\"+num).val();\r\n");
      out.write("            const gPrice = $(this).attr(\"data-price\");\r\n");
      out.write("           \t\r\n");
      out.write("            if(gAmount > 10) {\r\n");
      out.write("            \talert(\"수량을 10개 이하로 입력하세요.\");\r\n");
      out.write("            } else {\r\n");
      out.write("            \t$.ajax({\r\n");
      out.write("            \t\turl:'CartUpdateServlet',\r\n");
      out.write("            \t\ttype: 'get',\r\n");
      out.write("            \t\tdataType: 'text',\r\n");
      out.write("            \t\tdata: {\r\n");
      out.write("            \t\t\tnum,\r\n");
      out.write("            \t\t\tgAmount,\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\tsuccess:function(data, status, xhr){\r\n");
      out.write("            \t\t\tlet sum = gAmount*gPrice;\r\n");
      out.write("            \t\t\t$(\"#sum\"+num).text(sum); //span태그에 sum값 수정\r\n");
      out.write("            \t\t},\r\n");
      out.write("            \t\terror:function(xhr,status,error){\r\n");
      out.write("            \t\t\tconsole.log(\"error\");\r\n");
      out.write("            \t\t} \r\n");
      out.write("            \t}); //end ajax\r\n");
      out.write("            }// end if~else\r\n");
      out.write("        });// end event\r\n");
      out.write("        \r\n");
      out.write("        //전체 장바구니 삭제 1 \r\n");
      out.write("        $(\"#delAllCart1\").on(\"click\", () => {\r\n");
      out.write("        \tlet num = [];\r\n");
      out.write("        \t$(\"input:checkbox[name='check']:checked\").each((i,elem) => {\r\n");
      out.write("        \t\tnum[i] = $(elem).val();\r\n");
      out.write("        \t});\r\n");
      out.write("        \tlocation.href = \"CartDelAllServlet?data=\"+num; //삭제 할 상품의 num을 url로 전송\r\n");
      out.write("        }); //end 전체 삭제1\r\n");
      out.write("\r\n");
      out.write("    \t//전체 장바구니 삭제 2\r\n");
      out.write("    \t$(\"#delAllCart2\").on(\"click\", () => {\r\n");
      out.write("    \t\t$(\"form\").attr(\"action\", \"CartDelAllServlet2\");\r\n");
      out.write("    \t\t$(\"form\").submit(); //trigger (강제실행)\r\n");
      out.write("    \t}); //end 전체 삭제2\r\n");
      out.write("    \t\r\n");
      out.write("        //주문 버튼 \r\n");
      out.write("        $(\".orderBtn\").on(\"click\", function(){\r\n");
      out.write("        \tconsole.log(\"aaa\");\r\n");
      out.write("        \tconst num = $(this).attr(\"data-xxx\");\r\n");
      out.write("        \tlocation.href=\"CartOrderConfirmServlet?num=\"+num;\r\n");
      out.write("        });// end 주문 \r\n");
      out.write("\r\n");
      out.write("    });// end $ready\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"90%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"5\" class=\"td_default\">&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t<font size=\"5\"><b>- 장바구니-</b></font> &nbsp;\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"15\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"10\">\r\n");
      out.write("\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"7\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\">\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"allCheck\" id=\"allCheck\"> <strong>전체선택</strong>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\"><strong>주문번호</strong></td>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>상품정보</strong></td>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\"><strong>판매가</strong></td>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\" colspan=\"2\"><strong>수량</strong></td>\r\n");
      out.write("\t\t<td class=\"td_default\" align=\"center\"><strong>합계</strong></td>\r\n");
      out.write("\t\t<td></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"7\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"10\">\r\n");
      out.write("\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"myForm\">\r\n");

   //데이터 가져오기 //for문 작성 
   List<CartDTO> list = (List<CartDTO>)request.getAttribute("cartList");
	for(int i=0;i<list.size();i++){
		CartDTO dto = list.get(i);
		int num = dto.getNum();
		String userid = dto.getUserid();
		String gCode = dto.getgCode();
		String gName = dto.getgName();
		int gPrice = dto.getgPrice();
		String gSize = dto.getgSize();
		String gColor = dto.getgColor();
		int gAmount = dto.getgAmount();
		String gImage = dto.getgImage();
		

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"td_default\" width=\"80\">\r\n");
      out.write("\t\t\t\t<!-- checkbox는 체크된 값만 서블릿으로 넘어간다. 따라서 value에 삭제할 num값을 설정한다. --> \r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"check\" class=\"check\" value=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" width=\"80\">");
      out.print(num );
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" width=\"80\">\r\n");
      out.write("\t\t\t\t<img src=\"images/items/");
      out.print(gImage );
      out.write(".gif\" border=\"0\" align=\"center\" width=\"80\" />\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" width=\"300\" style='padding-left: 30px'><br>\r\n");
      out.write("\t\t\t\t<font size=\"2\" color=\"#665b5f\">[옵션 : 사이즈(");
      out.print( gSize);
      out.write(") , 색상(");
      out.print( gColor );
      out.write(")] </font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" align=\"center\" width=\"110\">");
      out.print(gPrice );
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" align=\"center\" width=\"90\">\r\n");
      out.write("\t\t\t\t<input class=\"input_default\" type=\"text\" name=\"cartAmount\" id=\"cartAmount");
      out.print(num );
      out.write("\"\r\n");
      out.write("\t\t\t\tstyle=\"text-align: right\" maxlength=\"3\" size=\"2\" value=\"");
      out.print(gAmount);
      out.write("\"></input>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td><input type=\"button\" value=\"수정\" class=\"updateBtn\" data-xxx=\"");
      out.print(num);
      out.write("\" data-price=\"");
      out.print(gPrice);
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" align=\"center\" width=\"80\" style='padding-left: 5px'>\r\n");
      out.write("\t\t\t<span id=\"sum");
      out.print(num);
      out.write('"');
      out.write('>');
      out.print(gPrice*gAmount );
      out.write("</span>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"주문\" class=\"orderBtn\" data-xxx=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"td_default\" align=\"center\" width=\"30\" style='padding-left: 10px'>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"삭제\" id=\"xx");
      out.print(i);
      out.write("\" class=\"delBtn\" data-xxx=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td height=\"10\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"10\">\r\n");
      out.write("\t\t\t<hr size=\"1\" color=\"CCCCCC\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"30\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\" colspan=\"5\">\r\n");
      out.write("\t\t<a class=\"a_black\" href=\"#\" id=\"orderAllConfirm\"> 선택 항목 주문하기 </a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a class=\"a_black\" href=\"#\" id=\"delAllCart1\"> 선택 항목 삭제하기</a>&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t<a class=\"a_black\" href=\"#\" id=\"delAllCart2\"> 선택 항목 삭제하기</a>&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t<a class=\"a_black\" href=\"main\"> 계속쇼핑하기 </a>&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"20\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
