/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-12 01:21:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.GoodsDTO;

public final class goodsRetrieve_005fstu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.GoodsDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

  //상품정보 파싱 
 	GoodsDTO dto = (GoodsDTO)request.getAttribute("goodsRetrieve");
	String gCode = dto.getgCode();
	String gImage = dto.getgImage();
	String gName = dto.getgName();
	int gPrice = dto.getgPrice();
	
	String str = (String) session.getAttribute("str");
	if(str!=null) { 

      out.write("  \r\n");
      out.write("\t<script>\r\n");
      out.write("\talert(\"");
      out.print(str);
      out.write("\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\t  \r\n");
 
	}
	session.removeAttribute("str");

      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    \t$(\"#cart\").on(\"click\", function() {\r\n");
      out.write("    \t\tif($(\"#gSize\").val() == \"사이즈선택\") {\r\n");
      out.write("    \t\t\talert(\"사이즈를 선택하세요.\");\r\n");
      out.write("    \t\t\tevent.preventDefault();\r\n");
      out.write("    \t\t} else if($(\"#gColor\").val() == \"색상선택\") {\r\n");
      out.write("    \t\t\talert(\"색상을 선택하세요.\");\r\n");
      out.write("    \t\t\tevent.preventDefault();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t$(\"#goodRetrieveForm\").attr(\"action\",\"GoodsCartServlet\");\r\n");
      out.write("    \t});  // end formSubmitEvent\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t//수량 증가버튼\r\n");
      out.write("    \tlet num = Number($(\"#gAmount\").val());\r\n");
      out.write("    \t$(\"#up\").on(\"click\", function() {\r\n");
      out.write("    \t\t$(\"#gAmount\").val(++num);\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t//수량 감소버튼\r\n");
      out.write("    \t$(\"#down\").on(\"click\", function() {\r\n");
      out.write("    \t\tif(num > 1) {\r\n");
      out.write("    \t\t\t$(\"#gAmount\").val(--num);\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}); //end\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t//상품 구매, 장바구니 저장\r\n");
      out.write("    \t\r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write("<form id=\"goodRetrieveForm\" name=\"goodRetrieveForm\" method=\"GET\">\r\n");
      out.write("\t    <!-- hidden  tag생성 -->\r\n");
      out.write("\t    <input type=\"hidden\" name=\"gCode\" value=\"");
      out.print(gCode );
      out.write("\">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"gImage\" value=\"");
      out.print(gImage );
      out.write("\">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"gName\" value=\"");
      out.print(gName );
      out.write("\">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"gPrice\" value=\"");
      out.print(gPrice );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\">\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table align=\"center\" width=\"710\" cellspacing=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\tborder=\"0\" style='margin-left: 30px'>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\"><font size=\"5\"><b>- 상품 정보 -</b></font>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"1\" colspan=\"8\" bgcolor=\"CECECE\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"10\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"7\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/items/");
      out.print(gImage );
      out.write(".gif\" border=\"0\" align=\"center\" width=\"300\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\">제품코드</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(gCode );
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\">상품명</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_default\" colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(gName );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\">가격</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_red\" colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("\t\t\t\t\t\t ");
      out.print(gPrice );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\">배송비</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font color=\"#2e56a9\" size=\"2\"style='padding-left: 30px'><b> 무료배송</b> </font> \r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\">(도서산간지역 별도 배송비 추가)</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\" rowspan=\"2\">상품옵션</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"select_change\" size=\"1\" name=\"gSize\" id=\"gSize\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value=\"사이즈선택\">사이즈선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"L\">L</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"M\">M</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S\">S</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style='padding-left: 30px'>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"select_change\" size=\"1\" name=\"gColor\" id=\"gColor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value=\"색상선택\">색상선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"navy\">navy</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"black\">black</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"ivory\">ivory</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"white\">white</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"gray\">gray</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_title\">주문수량</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding-left: 30px\">\r\n");
      out.write("\t\t\t\t\t    <input type=\"text\" name=\"gAmount\" value=\"1\" id=\"gAmount\" style=\"text-align: right; height: 18px\"> \r\n");
      out.write("\t\t\t\t\t    <img src=\"images/up.PNG\" id=\"up\"> <img src=\"images/down.PNG\" id=\"down\">\r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<br> <button onclick=\"reqCheck('order')\">구매</button>\r\n");
      out.write("\t&nbsp;&nbsp;\r\n");
      out.write("\t<button id=\"cart\" onclick=\"reqCheck('cart')\">장바구니</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
