/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-07 03:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.MemberDTO;

public final class myPage_005fstu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    ");
 
    String str = (String) session.getAttribute("str");
    if(str != null) {
     
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("   \talert(\"");
      out.print(str);
      out.write("\");\r\n");
      out.write("   \t\r\n");
      out.write("   </script>\r\n");
      out.write("    ");
 
    System.out.println(str);
    }
    session.removeAttribute("str");
    
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      \t//이메일 선택 입력\r\n");
      out.write("      \t$(\"#emailSelect\").on(\"change\", function() {\r\n");
      out.write("      \t\t$(\"#email2\").val($(\"#emailSelect\").val());\r\n");
      out.write("      \t}); //end\r\n");
      out.write("\t$(\"#passwd\").focus();\r\n");
      out.write(" });\r\n");
      out.write("</script>    \r\n");

  //session에서 "login"으로 데이터 뽑기 
  MemberDTO dto = (MemberDTO) session.getAttribute("login");
  String userid = dto.getUserid();
  String passwd = request.getParameter("passwd");
  String username = dto.getUsername();
  String post = dto.getPost();
  String addr1 = dto.getAddr1();
  String addr2 = dto.getAddr2();
  String phone1 = dto.getPhone1();
  String phone2 = dto.getPhone2();
  String phone3 = dto.getPhone3();
  String email1 = dto.getEmail1();
  String email2 = dto.getEmail2();
  

      out.write("\r\n");
      out.write("<form action=\"MemberUpdateServlet\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" value=\"");
      out.print(userid );
      out.write("\" name=\"userid\">\r\n");
      out.write("*아이디: ");
      out.print(userid  );
      out.write("<br>\r\n");
      out.write("*비밀번호 확인 : <input id=\"passwd\" type=\"password\" value=\"\" name=\"passwd\"><br>\r\n");
      out.write("*이름:");
      out.print(username  );
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" value=\"");
      out.print(post );
      out.write("\" name=\"post\" id=\"sample4_postcode\"  placeholder=\"우편번호\">\r\n");
      out.write("<input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("<input type=\"text\" value=\"");
      out.print(addr1 );
      out.write("\" name=\"addr1\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\">\r\n");
      out.write("<input type=\"text\" value=\"");
      out.print(addr2 );
      out.write("\" name=\"addr2\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\">\r\n");
      out.write("<span id=\"guide\" style=\"color:#999\"></span>\r\n");
      out.write("<br>\r\n");
      out.write("전화번호:<select name=\"phone1\">\r\n");
      out.write("  <option value=\"017\" ");
if("017".equals(phone1)){ 
      out.write("selected");
} 
      out.write(">017</option>\r\n");
      out.write("  <option value=\"011\" ");
if("011".equals(phone1)){ 
      out.write("selected");
} 
      out.write(">>011</option>\r\n");
      out.write("  <option value=\"010\" ");
if("010".equals(phone1)){ 
      out.write("selected");
} 
      out.write(">010</option>\r\n");
      out.write("\r\n");
      out.write("</select>-\r\n");
      out.write("<input type=\"text\" value=\"");
      out.print(phone2 );
      out.write("\" name=\"phone2\" >\r\n");
      out.write("-<input type=\"text\" value=\"");
      out.print(phone3 );
      out.write("\" name=\"phone3\" >\r\n");
      out.write("<br>\r\n");
      out.write("이메일:<input type=\"text\" value=\"");
      out.print(email1 );
      out.write("\" name=\"email1\" id=\"email1\">@\r\n");
      out.write("       <input type=\"text\" value=\"");
      out.print(email2 );
      out.write("\" name=\"email2\" id=\"email2\" placeholder=\"직접입력\">\r\n");
      out.write("       <select  id=\"emailSelect\">\r\n");
      out.write("        <option value=\"daum.net\" ");
if("daum.net".equals(email2)){ 
      out.write("selected");
} 
      out.write(">daum.net</option>\r\n");
      out.write("        <option value=\"naver.com\" ");
if("naver.com".equals(email2)){ 
      out.write("selected");
} 
      out.write(">naver.com</option>\r\n");
      out.write("       </select>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"회원정보 수정\">\r\n");
      out.write("</form>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var fullRoadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 도로명 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraRoadAddr !== ''){\r\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("                // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\r\n");
      out.write("                if(fullRoadAddr !== ''){\r\n");
      out.write("                    fullRoadAddr += extraRoadAddr;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                document.getElementById('sample4_roadAddress').value = fullRoadAddr;\r\n");
      out.write("                document.getElementById('sample4_jibunAddress').value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                if(data.autoRoadAddress) {\r\n");
      out.write("                    //예상되는 도로명 주소에 조합형 주소를 추가한다.\r\n");
      out.write("                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                } else if(data.autoJibunAddress) {\r\n");
      out.write("                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("\r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById('guide').innerHTML = '';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
