SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE 'A%';
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '%A';
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '%T%';
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '_L%';
-- 문자열에 패턴 매칭 연산자가 포함 된 경우
SELECT EMPNO, ENAME, JOB FROM EMP WHERE ENAME LIKE '%\_%' ESCAPE '\';
-- EMP 테이블에서 JOB이 'CLERK'이거나 'ANALYST'이고,
-- COMM이 NULL이고 SAL가 1000보다 크고 3000보다 작은 사원 정보
SELECT * FROM EMP WHERE (JOB = 'CLERK' OR JOB = 'ANALYST') AND
COMM IS NULL AND SAL >= 1000 AND SAL <= 3000 ; 

SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE; -- 기본값 ASC(오름차순)
SELECT EMPNO, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC; -- 내림차순
SELECT EMPNO, ENAME, SAL * 12 "ANNUAL" FROM EMP ORDER BY "ANNUAL";
SELECT EMPNO, ENAME, SAL * 12 "ANNUAL" FROM EMP ORDER BY 3; -- 세번째 컬럼 기준
SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL DESC, EMPNO; -- SAL기준 정렬 후 EMPNO기준 정렬
